
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: dev_nb/CannyEdgeDetection.ipynb
import numpy as np

from Export.nb_Convolutions1D import *
from Export.nb_PixelManipulation import *

def horizontalSobel(img : np.array, blur_conv : np.array, edge_conv : np.array):
    img = oneDimConvolution(img, blur_conv, False, 255)
    return oneDimConvolution(img, edge_conv, True, 255)

def verticalSobel(img : np.array, blur_conv : np.array, edge_conv : np.array):
    img = oneDimConvolution(img, blur_conv, True, 255)
    return oneDimConvolution(img, edge_conv, False, 255)